name: panos_management_wait_for_device

label: 'Wait For Device Ready'

description: |
  Ensures a PAN-OS device is booted and available

type: python3

labels:
  collection:
    - PAN-OS Device Management

variables:
  - name: target_username
    description: Username
    default: admin
    type_hint: text
  - name: target_password
    description: Password
    default:
    type_hint: password
  - name: target_ip
    description: PAN-OS Device IP / Hostname
    default: 10.10.10.10
    type_hint: password
  - name: timeout
    description: Time to wait
    default: 10
    type_hint: text

snippets:
  - name: script
    file: ../../wait_for_device.py
    input_type: cli
