name: panos_management_load_baseline
label: Restore Configuration to Baseline
description: |
    Loads a configuration that is essentially a factory default, however the admin user and network settings are
    preserved.
type: python3
labels:
    collection: PAN-OS Device Management
variables:
-   name: target_ip
    description: PAN-OS Device IP / Hostname
    default: 10.10.10.10
    type_hint: fqdn_or_ip
    help_text: ''
-   name: target_username
    description: Username
    default: admin
    type_hint: text
-   name: target_password
    description: Password
    default: null
    type_hint: password
snippets:
-   name: script
    file: ../../load_baseline.py
    input_type: cli
