name: panos_management_deactivate_license
label: Deactivate VM-Series License
description: |
    Deactivates all licenses from a PAN-OS VM-Series instance.
type: python3
labels:
    collection: PAN-OS Device Management
variables:
-   name: target_ip
    description: PAN-OS Device IP / Hostname
    default: 10.10.10.10
    type_hint: fqdn_or_ip
    help_text: ''
-   name: target_username
    description: Username
    default: admin
    type_hint: text
-   name: target_password
    description: Password
    default: null
    type_hint: password
-   name: support_api_key
    description: Support API Key
    default: null
    type_hint: password
    help_text: This key can be found in the support.paloaltonetworks.com site under
        Assets -> Licensing API
snippets:
-   name: script
    file: ../../deactivate_license.py
    input_type: cli
