name: panos_management_update_dynamic_content
label: Update and install Dynamic Content to latest version
description: |
    Checks for updates to dynamic content and installs the latest if necessary.
type: python3
labels:
    collection: PAN-OS Device Management
variables:
-   name: target_ip
    description: PAN-OS Device IP / Hostname
    default: 10.10.10.10
    type_hint: fqdn_or_ip
    help_text: ''
-   name: target_username
    description: Username
    default: admin
    type_hint: text
-   name: target_password
    description: Password
    default: null
    type_hint: password
-   name: content_type
    description: Dynamic Content Type
    default: Content
    type_hint: dropdown
    dd_list:
    -   key: content
        value: Content
    -   key: anti-virus
        value: Anti-Virus
    -   key: wildfire
        value: Wildfire
snippets:
-   name: script
    file: ../../update_dynamic_content.py
    input_type: cli
